### ISSUE TITLE
Loading project always fail

### ISSUE THREAD

**Issue by imspikey** [Click2Cloud/openshift-tool-visualstudio#1]
Hello 
at the moment not one project opens successfully all what I get when I open a project is a solution with two empty folder 
Solution Items: contains only: global.json
SRC: contains aspnet-core-1.0.0-helloworld -> and when I open it I get the message the project file cannot be loaded???!!!
I am using visual studio 2015 update 3 on windows 8.1
any help please.

**Comment by shrutikamendhe** [comment]
Hello @imspikey 

Can you please verify, if you have also installed [.NET Core 1.0.0 - VS 2015 Tooling Preview 2](https://go.microsoft.com/fwlink/?LinkId=817245) along with Visual Studio 2015 Update 3. It is required to load ASP.NET Core 1.0.0 application in  Visual Studio. 

You can find more detail at https://www.microsoft.com/net/core#windows.
